services:
  - type: web
    name: awad-email-backend
    runtime: docker
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRATION
        value: 3600000
      - key: JWT_REFRESH_TOKEN_EXPIRATION
        value: 86400000
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false

